"""add_status_to_lesson

Revision ID: 76529d5f5aa0
Revises: d1b32a19289c
Create Date: 2026-05-14 18:22:38.105179
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '76529d5f5aa0'
down_revision = 'd1b32a19289c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='queued'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'status')
    # ### end Alembic commands ###
