"""rename_lesson_type_to_content_type

Revision ID: c2e44264211a
Revises: 76529d5f5aa0
Create Date: 2026-05-14 18:24:03.442281
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c2e44264211a'
down_revision = '76529d5f5aa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'lesson_type', new_column_name='content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'content_type', new_column_name='lesson_type')
    # ### end Alembic commands ###
